### PR TITLE
Upcoming elections

### PR DESCRIPTION
**Pull request by adborden**
Here's the scaffolding for the upcoming elections page, fixes https://github.com/caciviclab/disclosure-backend/issues/26.

Last week we dropped the tabs from the design, but I left them in for now until we have a new design. This page uses `appMian.city` as it's parent, shared with `appMain.city.money`. The title and tab nav were split into the parent's template.

I used ui-bootstrap-tabs for the tab navigation as per @jnmarcus 's suggestion, but their use case isn't quite what we're after. We're using them purely as UI elements, but ui-boostrap-tabs also handles the content switching logic, which we're mostly just working around in our case. The main reason for this is that we actually want to trigger a ui-router stage change, but ui-bootstrap-tabs doesn't support that first class. Luckily, since we're dropping tabs from the design, we'll end up removing ui-boostrap-tabs anyway.

[Screenshot](https://cloud.a14n.net/index.php/s/LPVT6IV1vqSnioI).
screenshot

### CODE REVIEW

**Comment by tdooner** [comment]
:+1:

**Comment by adborden** [comment]
@jnmarcus requested these pages be moved under `appMainModule`

**Comment by bcipolli** [comment]
@adborden Does it make sense to mock up the front-end data access here, or to defer that to another PR?

**Comment by adborden** [comment]
@bcipolli that's a good point. I'll add it.

**Comment by adborden** [comment]
@bcipolli added.

**Pull request merged**
