### PR TITLE
Move pages under appMain part I

### PR DESCRIPTION
**Pull request by adborden**
Moves the measure module under `appMain`. Creates page controllers to handle the glue between the state routing/data resolving and the component directives.

The components:
- measureListing - describes the ballot measure name, text, and number.
- measureCommitteeListing - lists out committees that have contributed on a ballot measure.
- measureCommitteeOpposing - lists out committees opposing a ballot measure.
- measureCommitteeSupporting - lists out committees supporting a ballot measure.

No UI changes.

cc @jnmarcus

### CODE REVIEW

**Comment by adborden** [comment]
Part I of #62

**Comment by bcipolli** [comment]
This seems like a good time to ask: is there a master list of:
* The routes expected
* What their JSON expected format is, if defined
?

If not, can we use this as an opportunity to start one, for the set of routes being touched here?

**Comment by adborden** [comment]
@bcipolli 

> - The routes expected
> - What their JSON expected format is, if defined ?

Not sure I understand the question. Are you referring to the routes/data on the frontend or the routes/data of the API?

For the fronted: No, I'm creating routes that seem appropriate based on the mockups. The data models are also based on the mockups, but in some cases I'm looking at the existing django models on the backend as a guide.

For the API: No, we've discussed casually that part of the django API should be view-focused, that is, it should return data specifically for the view independent of how the data is modeled in the database. At least in my head, these would be the endpoints that live in the `disclosure` app described in the [Database Schema Design wiki](https://github.com/caciviclab/caciviclab.github.io/wiki/Data-relationships---Database-schema#disclosure-app).

But my primary focus of the recent PRs is getting a broad scaffold of the app up so that

1. New folks can see where they would implement features.
2. We can get something to demo and play around with.

and also meets @jnmarcus 's component-style design requirements.

**Comment by bcipolli** [comment]
@jnmarcus Can you provide a quick update if you want to give feedback on these? We're to the stage where we can build back-end APIs, and we should work with the latest front-end code.

If there's nobody to review these today or tomorrow, I'm of the mind to merge them and focus on putting each of these on top of a live API call. We're basically there!

**Comment by bcipolli** [comment]
I need to browse this code and try to get the back-end going, so... better to merge and work with the latest. It's been almost 2 weeks!

**Pull request merged**
