### PR TITLE
Measure module

### PR DESCRIPTION
**Pull request by adborden**
This adds the scaffolding for the ballot measure page, fixes https://github.com/caciviclab/disclosure-backend/issues/27.

This follows a slightly different directory structure. It's all based in the measureModule, but has several templates and controllers, each grouped under a `templates` and `controllers` dir, respectively. There's an abstract state at the root to handle the API call and the breadcrumbs. The other three pages, (index, supporting, opposing) are children of the abstract state, inheriting it's properties.

### CODE REVIEW

**Comment by adborden** [comment]
Screenshots...
[Ballot measure index](https://cloud.a14n.net/index.php/s/ifxup9HFHg1A6lP)
Ballot measure index screenshot

[Opposing committees](https://cloud.a14n.net/index.php/s/jra2DHkONhpp52k)
Opposing committees screenshot

[Supporting committees](https://cloud.a14n.net/index.php/s/bYjQhXyKDuRM2Sf)
Supporting committees screenshot

**Comment by jnmarcus** [comment]
@adborden all of the controllers you loaded into the measure module should probably be their own components, with their own directives.  Also, moving files into 'templates' and 'controllers' directories tends to de-componentize projects

**Comment by jnmarcus** [comment]
Additionally, the measure module itself should probably be a component, that can be called in on the city, county, and state pages.  I don't think it needs it's own page (in UI router's sake at least)

**Comment by adborden** [comment]
I'll try pulling the different pages apart into their own components, but I don't see how these are not their own pages. Given that each has it's own route (and state), shouldn't they be implemented as a page?

Maybe if you can give me an example of what you're looking for?

**Comment by adborden** [comment]
Oh, I think I know what you're getting at... I think I'm going to open an issue for this refactor since I have to clean up the other modules as well.

**Pull request merged**
