### PR TITLE
Hashbang routing

### PR DESCRIPTION
**Pull request by adborden**
Route using hashbangs so we can live on github pages for a while.

### CODE REVIEW

**Comment by adborden** [comment]
This PR makes us github pages ready :)

**Comment by tdooner** [comment]
Not sure I understand the necessity for the relative URLs for the assets, but otherwise :+1:

**Comment by adborden** [comment]
The relative urls aren't really necessary anymore. They were needed when hosting at http://caciviclab.github.io/disclosure-frontend-alpha/

**Comment by adborden** [comment]
@jnmarcus asked to remove the base-url which won't really be necessary going forward.

**Pull request merged**
